export interface ChatVariant {
  content: string;
  thinking?: string;
  usage?: TokenUsage;
  attachments?: Attachment[]; // e.g. images generated by an image-output model in this variant
}

/** Message attachment: image, document (PDF…) in base64, or text file. */
export interface Attachment {
  kind: 'image' | 'text' | 'document';
  name: string;
  mime: string;
  data?: string; // resolved content (in memory / wire / webview)
  ref?: string;  // id of the entry in the .attach sidecar (what gets saved in the .chat file)
  bytes?: number; // size of the resolved content; kept on ref-only attachments for token budgeting
}

export interface ToolSchema {
  name: string;
  description?: string;
  parameters: Record<string, unknown>; // JSON Schema
}

export interface ToolCall {
  id: string;
  name: string;
  arguments: string; // JSON-serialized arguments
}

export interface TokenUsage {
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
  cost?: number; // cost in USD, if the backend reports it (OpenRouter)
}

export interface ChatMessage {
  role: 'system' | 'user' | 'assistant' | 'tool';
  content: string;
  id?: string; // stable message identifier
  ts?: string; // ISO 8601 creation timestamp
  usage?: TokenUsage; // tokens used (in assistant responses)
  /** Model reasoning. Stored for display, but NOT forwarded to the backend. */
  thinking?: string;
  attachments?: Attachment[];
  /** Tool calls requested by the assistant. */
  toolCalls?: ToolCall[];
  /** For 'tool' role messages: id of the call being answered and name of the tool. */
  toolCallId?: string;
  toolName?: string;
  /** Variants generated by reprocessing (assistant only). content/thinking reflect the active one. */
  variants?: ChatVariant[];
  active?: number;
}

/**
 * Generation parameters. All optional: only the ones the user has enabled
 * in the `.chat` file are sent to the backend.
 */
export interface GenerationParams {
  temperature?: number;
  maxTokens?: number; // response token limit
  topK?: number;
  topP?: number;
  minP?: number;
  topA?: number; // OpenRouter sampler
  repeatPenalty?: number;
  presencePenalty?: number;
  frequencyPenalty?: number;
  seed?: number;
  stop?: string[];
  numThreads?: number; // num_thread (Ollama)
  contextLength?: number; // num_ctx (Ollama)
  thinking?: boolean; // enables reasoning mode in Ollama (think: true)
  tools?: ToolSchema[]; // available tools (function calling)
}

export interface StreamCallbacks {
  onDelta: (text: string) => void; // response content
  onReasoning?: (text: string) => void; // reasoning (thinking)
  signal: AbortSignal;
}

export interface ModelInfo {
  id: string;
  contextLength?: number; // context window size in tokens, if the backend exposes it
  // Capabilities (as declared by the backend):
  vision?: boolean;
  files?: boolean;
  audio?: boolean;
  tools?: boolean;
  reasoning?: boolean;
}

/** An image produced by an image-output model (e.g. Gemini "nano-banana"), base64-encoded. */
export interface GenImage {
  mime: string;
  data: string;
}

export interface ChatResult {
  answer: string;
  thinking: string;
  toolCalls?: ToolCall[]; // if the model requested tool execution
  usage?: TokenUsage; // tokens reported by the backend
  images?: GenImage[]; // images returned by an image-output model
}

/**
 * Common abstraction for any LLM backend (OpenAI-compatible or Ollama).
 */
export interface LLMProvider {
  readonly id: string;
  /** Lists the models available in the backend. */
  listModels(): Promise<ModelInfo[]>;
  /** Generates a streaming response. Returns response and reasoning separately. */
  chat(
    model: string,
    messages: ChatMessage[],
    params: GenerationParams,
    cb: StreamCallbacks
  ): Promise<ChatResult>;
}
